title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
theme: minima

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

# Society info
society:
  name: Asociación de Robótica UC3M
  short_name: ASROB
  email: 
  # Social networking links used in footer. Update and remove as you like.
  # (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
  social:
      - id: github
        name: GitHub
        url: 
      - id: twitter
        name: Twitter
        url:
      - id: facebook
        name: Facebook   
        url:
      - id: linkedin
        name: Linkedin
        url:
      - id: google_plus
        name: Google+
        url:
      - id: envelope
        name: Email
        url: 

more_info:
  - title: Antiguos proyectos
    description: Some quick example text to build on the card title and make up the bulk of the card's content.
    url: 
    picture: http://placehold.it/150x150

  - title: Gestión de impresoras 3D
    description: Some quick example text to build on the card title and make up the bulk of the card's content.
    url: 
    picture: http://placehold.it/150x150

  - title: Miembros
    description: Some quick example text to build on the card title and make up the bulk of the card's content.
    url: 
    picture: http://placehold.it/150x150

  - title: Tutoriales
    description: Some quick example text to build on the card title and make up the bulk of the card's content.
    url: 
    picture: http://placehold.it/150x150

  - title: Repositorios
    description: Some quick example text to build on the card title and make up the bulk of the card's content.
    url: 
    picture: http://placehold.it/150x150

  - title: Wiki
    description: Some quick example text to build on the card title and make up the bulk of the card's content.
    url: 
    picture: http://placehold.it/150x150

# Collections
collections:
   news:
     my_title: News
    
