---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "ASROB"
keywords:    "asrob, robots, uavs, myod, robot devastation, robotics"
description: "Sitio web de la Asociación de Robótica UC3M (ASROB)"
source_link: "/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: 
permalink : /:year

### template colors, used site-wide via css ###
colors:
  black:     '#454545' #111111
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  asrob1:    '#f8f8f8'
  asrob2:    '#c869bf'
  red:       '#891717'
  gray:      '#cccccc'

kramdown:
  auto_ids:  false


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/user/asrobuc3m/
  - title: twitter
    url: https://twitter.com/asrob_uc3m
  - title: facebook
    url: http://www.facebook.com/pages/Asociacion-de-Robotica-UC3M/170784706272131
  - title: google-plus 
    url: https://plus.google.com/117320353227938266035
  - title: envelope
    url : mailto:uc3music@gmail.com 
  - title: github
    url: http://github.com/asrob-uc3m
  - title: linkedin
    url: https://www.linkedin.com/in/asrobuc3m
