baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
repo_url: "https://github.com/asrob-uc3m/asrob-uc3m.github.io"

# Build settings
markdown: kramdown
theme: minima

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

# Society info
society:
  name: Asociación de Robótica UC3M
  short_name: ASROB
  email: asrob-uc3m@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  # (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
  social:
      - id: telegram
        name: Telegram
        url: https://t.me/joinchat/ADT1EAgigvgsuobGUHMl_w
      - id: github
        name: GitHub
        url: https://github.com/asrob-uc3m
      - id: youtube
        name: YouTube
        url: http://www.youtube.com/user/asrobuc3m/featured
      - id: twitter
        name: Twitter
        url: http://twitter.com/asrob_uc3m
      - id: instagram
        name: Instagram
        url: https://www.instagram.com/asrob_uc3m
      - id: linkedin
        name: Linkedin
        url: https://www.linkedin.com/in/asrobuc3m
      - id: envelope
        name: Email
        url: mailto:asrob.uc3m@gmail.com

  management:
      president:
          name: Juan
          github: jgvictores
      secretary: 
          name: Isabel
          github: Isaa101
      treasurer: 
          name: Aina
          github: aina-c
      printers:
          name: elfantasmadeasrob
          github: elfantasmadeasrob
      mails:
          name: Juan
          github: jgvictores
      social:
        - name: Guillermo - Twitter
          github: guillermogarcia251
        - name: Bartek - Instagram
          github: PeterBowman

# More info: these are the links to the main sections of the website
more_info:
  - title: Antiguos grupos de trabajo
    description: Proyectos que se llevaron a cabo en ASROB, pero que actualmente no cuentan con un Grupo de Trabajo Activo.
    url: /old-workgroups.html
    picture: /img/old_projects.png

  - title: Gestión de impresoras 3D
    description: En ASROB disponemos de varias impresoras 3D. Entérate aquí sobre cómo usarlas.
    url: https://apps-robots.uc3m.es/asrob/printers
    picture: /img/printers.png

  - title: Miembros
    description: Aquí se encuentra el Listado de Socios con Puesto de Responsabilidad, así como los Antiguos Miembros y el Hall of Fame. Para un listado de socios actuales, revisa las páginas de cada grupo activo.
    url: /members.html
    picture: /img/members.png

  - title: Tutoriales
    description: Recopilación de tutoriales y materiales útiles sobre los programas y herramientas que usamos en ASROB.
    url: https://asrob-uc3m.gitbooks.io/tutoriales/content
    picture: /img/tutorials.png

  - title: Repositorios
    description: ¡Nuestro código es libre! Puedes echarle un ojo aquí para aprender, contribuir o simplemente curiosear.
    url: https://github.com/asrob-uc3m
    picture: /img/repos.png

  - title: Wiki
    description: Ahora tenemos esta web, pero mucha de la documentación de ASROB sigue estando en la wiki.
    url: https://apps-robots.uc3m.es/asrob/wiki
    picture: /img/wiki.png

# other links: links to other useful resources
other_links:
  - name: Calendario
    url: https://calendar.google.com/calendar/embed?src=e97mebpnhjcq8pbl28plc8l3is%40group.calendar.google.com&ctz=Europe/Madrid
  - name: Contributors
    url: https://apps-robots.uc3m.es/asrob/contributors
  - name: Trophies & Awards
    url: /awards.html
  - name: Lista de Correo
    url: https://groups.google.com/forum/#!forum/miembros-activos-asrob

# collaborations: people that supports us
collaborations:
  - name: UC3M
    url: https://www.uc3m.es
    picture: img/collaborators/uc3m.png
  - name: RoboticsLab
    url: https://roboticslab.uc3m.es
    picture: img/collaborators/roboticslab.png
  - name: Robocity2030
    url: https://www.robocity2030.org/branches/
    picture: img/collaborators/robocity.png

# Collections
collections:
    news:
        title: Noticias
    workgroups:
        title: Grupos de Trabajo Activos
        output: true
    old_workgroups:
        title: Antiguos Grupos de Trabajo
        output: true
    projects:
        title: Proyectos
        output: true
    awards:
        title: Premios y trofeos
        output: false
    redirects:
        output: true
